# Java 自定义异常

> 原文：<https://www.javatpoint.com/custom-exception>

在 Java 中，我们可以创建自己的异常，这些异常是异常类的派生类。创建我们自己的异常被称为自定义异常或用户定义异常。基本上，Java 自定义异常是用来根据用户需要自定义异常的。

考虑示例 1，其中 InvalidAgeException 类扩展了异常类。

使用自定义异常，我们可以拥有您自己的异常和消息。这里，我们已经将一个字符串传递给了超类的构造函数，即可以使用 getMessage()方法在我们创建的对象上获得的异常类。

在本节中，我们将学习如何在 Java 程序中实现和使用自定义异常。

## 为什么要使用自定义异常？

Java 异常几乎涵盖了编程中可能出现的所有一般类型的异常。然而，我们有时需要创建自定义异常。

以下是使用自定义异常的一些原因:

*   捕捉并提供对现有 Java 异常子集的特定处理。
*   业务逻辑异常:这些是与业务逻辑和工作流相关的异常。对于应用程序用户或开发人员来说，了解确切的问题是很有用的。

为了创建自定义异常，我们需要扩展属于 java.lang 包的 exception 类。

考虑以下示例，其中我们创建了一个名为“错误文件名异常”的自定义异常:

```

public class WrongFileNameException extends Exception {
	public WrongFileNameException(String errorMessage) {
	super(errorMessage);
	}
}

```

#### 注意:我们需要编写一个以字符串作为错误信息的构造函数，它被称为父类构造函数。

### 例 1:

让我们看一个简单的 Java 自定义异常的例子。在下面的代码中，InvalidAgeException 的构造函数将字符串作为参数。使用 super()方法将该字符串传递给父类 Exception 的构造函数。此外，可以在不使用参数的情况下调用异常类的构造函数，并且调用 super()方法不是必需的。

**testcustomexception 1 . Java**

```

// class representing custom exception
class InvalidAgeException  extends Exception
{
    public InvalidAgeException (String str)
    {
        // calling the constructor of parent Exception
        super(str);
    }
}

// class that uses custom exception InvalidAgeException
public class TestCustomException1
{

    // method to check the age
    static void validate (int age) throws InvalidAgeException{  
       if(age < 18){

        // throw an object of user defined exception
        throw new InvalidAgeException("age is not valid to vote");  
    }
       else { 
        System.out.println("welcome to vote"); 
        } 
     }  

    // main method
    public static void main(String args[])
    {
        try
        {
            // calling the method 
            validate(13);
        }
        catch (InvalidAgeException ex)
        {
            System.out.println("Caught the exception");

            // printing the message from InvalidAgeException object
            System.out.println("Exception occured: " + ex);
        }

        System.out.println("rest of the code...");  
    }
}

```

**输出:**

![Java Custom Exception](../img/78ab63e42b8cf3a01189d37bc89820d2.png)

### 例 2:

**testcustomexception 2 . Java**

```

// class representing custom exception
class MyCustomException extends Exception
{

}

// class that uses custom exception MyCustomException
public class TestCustomException2
{
    // main method
    public static void main(String args[])
    {
        try
        {
            // throw an object of user defined exception
            throw new MyCustomException();
        }
        catch (MyCustomException ex)
        {
            System.out.println("Caught the exception");
            System.out.println(ex.getMessage());
        }

        System.out.println("rest of the code...");  
    }
}

```

**输出:**

![Java Custom Exception](../img/7bed5e7192db204150d4e4b3d73b6044.png)

* * *