# Java 9 尝试资源增强

> 原文：<https://www.javatpoint.com/java-9-try-with-resources>

Java 在 Java 7 中引入了**资源试用**功能，帮助资源使用后自动关闭。

换句话说，我们可以说，我们不需要显式关闭资源(文件、连接、网络等)，而是使用自动关闭接口自动尝试关闭资源。

在 Java 7 中，尝试使用资源有一个限制，要求资源在其块内进行本地声明。

**在资源块中声明的示例 Java 7 资源**

```
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
public class FinalVariable {
	public static void main(String[] args) throws FileNotFoundException {
		try(FileOutputStream fileStream=new FileOutputStream("javatpoint.txt");){
			 String greeting = "Welcome to javaTpoint.";    
		        byte b[] = greeting.getBytes();     
		        fileStream.write(b);    
		        System.out.println("File written");       	
		}catch(Exception e) {
			System.out.println(e);
		}		
	}
}

```

Java 7 甚至 Java 9 都可以很好地执行这段代码，因为 Java 保持了它的传统。

但是下面的程序不适用于 Java 7，因为**我们不能将声明的资源放在资源尝试之外。**

* * *

### 在资源块外声明的 Java 7 资源

如果我们确实喜欢 Java 7 中的以下代码，编译器会生成一条错误消息。

```
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
public class FinalVariable {
	public static void main(String[] args) throws FileNotFoundException {
		FileOutputStream fileStream=new FileOutputStream("javatpoint.txt");
		try(fileStream){
			 String greeting = "Welcome to javaTpoint.";    
		        byte b[] = greeting.getBytes();     
		        fileStream.write(b);    
		        System.out.println("File written");       	
		}catch(Exception e) {
			System.out.println(e);
		}		
	}
}

```

输出:

```
error: <identifier> expected
		   try(fileStream){

```

为了处理这个错误，在 Java 9 中对 try-with-resource 进行了改进，现在我们可以使用未在本地声明的资源的引用。

在这种情况下，**如果我们使用 Java 9 编译器执行上面的程序，它将很好地执行，没有任何编译错误。**

* * *

### Java 9 资源试用示例

```
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
public class FinalVariable {
	public static void main(String[] args) throws FileNotFoundException {
		FileOutputStream fileStream=new FileOutputStream("javatpoint.txt");
		try(fileStream){
			 String greeting = "Welcome to javaTpoint.";    
		        byte b[] = greeting.getBytes();     
		        fileStream.write(b);    
		        System.out.println("File written");       	
		}catch(Exception e) {
			System.out.println(e);
		}		
	}
}

```

输出:

```
File written

```