# Java 7 捕捉多个异常

> 原文：<https://www.javatpoint.com/java-7-catch-multiple-exceptions>

Java 允许您在一个 catch 块中捕获多个类型异常。它是在 Java 7 中引入的，有助于优化代码。

您可以使用竖线(|)来分隔 catch 块中的多个异常。

Java 7 之前处理多个异常的旧方法。

### 捕捉多个异常类型示例 1

```java
public class MultipleExceptionExample{  
	public static void main(String args[]){  
		try{  
			int array[] = newint[10];  
			array[10] = 30/0;  
		}  
		catch(ArithmeticException e){
			System.out.println(e.getMessage());
		}  
		catch(ArrayIndexOutOfBoundsException e){
			System.out.println(e.getMessage());
		}  
		catch(Exception e){
			System.out.println(e.getMessage());
		}  
	 }  
}

```

输出:

```java
/ by zero

```

* * *

## 捕捉多个异常类型示例 2

Java 7 为我们提供了什么:

```java
public class MultipleExceptionExample{  
	public static void main(String args[]){  
		try{  
			int array[] = newint[10];  
			array[10] = 30/0;  
		}  
		catch(ArithmeticException | ArrayIndexOutOfBoundsException e){
			System.out.println(e.getMessage());
		}  
	 }  
}

```

输出:

```java
/ by zero

```

* * *

## 捕捉多个异常类型示例 3

```java
public class MultipleExceptionExample{  
	public static void main(String args[]){  
		try{  
			int array[] = newint[10];  
			array[10] = 30/0;  
		}  
		catch(Exception | ArithmeticException | ArrayIndexOutOfBoundsException e){
			System.out.println(e.getMessage());
		}  
	 }  
}

```

输出:

```java
Compile-time error: The exception ArithmeticException is already caught by the alternative Exception

```

因此，在这里，如果您捕捉到多个异常，请遵循一般化到更专门化的规则。这意味着，如果你使用的是超级(普通)类，不要使用子(专业)类。

#### 注意-处理多个异常类型的 catch 块使 Catch 参数隐式成为最终参数。在上面的例子中，catch 参数“e”是最终的，因此不能给它赋值。